server:
  port: 8080

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.pojo
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
feign:
  httpclient:
    enabled: true                 #開啟 feign 對 httpclient 的支持
    max-connections: 5            #最大連接數
    max-connections-per-route: 10 #每條線最大連線數
